import type { StoryModeProfile } from "@write-now/shared/types/storyMode";

export interface StoryModeSeedNode {
  id: string;
  name: string;
  description: string;
  template: string;
  profile: StoryModeProfile;
  children: Array<{
    id: string;
    name: string;
    description: string;
    template: string;
    profile: StoryModeProfile;
  }>;
}

function buildProfile(input: Partial<StoryModeProfile> & Pick<StoryModeProfile, "coreDrive" | "readerReward">): StoryModeProfile {
  return {
    coreDrive: input.coreDrive,
    readerReward: input.readerReward,
    progressionUnits: input.progressionUnits ?? ["关系推进", "阶段目标兑现"],
    allowedConflictForms: input.allowedConflictForms ?? ["与主驱动一致的中低烈度冲突"],
    forbiddenConflictForms: input.forbiddenConflictForms ?? ["无关的高压狗血冲突"],
    conflictCeiling: input.conflictCeiling ?? "medium",
    resolutionStyle: input.resolutionStyle ?? "优先用符合该模式的方式解决问题，而不是强行升级矛盾。",
    chapterUnit: input.chapterUnit ?? "每章围绕一个清晰推进单位展开。",
    volumeReward: input.volumeReward ?? "卷末给出阶段性兑现，让读者确认这条线值得继续追。",
    mandatorySignals: input.mandatorySignals ?? ["主驱动持续出现", "读者期待被反复确认"],
    antiSignals: input.antiSignals ?? ["长期偏离主驱动", "冲突烈度失控"],
  };
}

export const BUILT_IN_STORY_MODE_SEEDS: StoryModeSeedNode[] = [
  {
    id: "story_mode_power_root",
    name: "爽感推进",
    description: "以优势兑现、立威、反差和阶段性压制为主驱动力的阅读模式。",
    template: "强调优势展示、局势翻转和清晰的读者爽点兑现。",
    profile: buildProfile({
      coreDrive: "通过主角优势兑现、认知反差和局势翻转持续制造爽感。",
      readerReward: "读者持续看到压制、立威、反转和规则被改写的满足感。",
      progressionUnits: ["立威", "打破质疑", "扩大影响力", "阶段性碾压"],
      allowedConflictForms: ["身份压制", "认知偏差", "权力挑战", "规则重写"],
      forbiddenConflictForms: ["长期弱势求生", "持续吃瘪不反击"],
      conflictCeiling: "high",
      resolutionStyle: "尽快兑现主角优势，让冲突成为展示力量与地位的舞台。",
      chapterUnit: "每章推进一次压制、反转或立威结果。",
      volumeReward: "卷末形成更大范围的承认、恐惧、臣服或秩序改写。",
      mandatorySignals: ["优势感", "反差感", "立威场面"],
      antiSignals: ["主角长期被动", "爽点迟迟不兑现"],
    }),
    children: [
      {
        id: "story_mode_invincible",
        name: "无敌流",
        description: "主角优势非常明确，悬念来自展示方式和秩序改写，而不是生存危机。",
        template: "尽快立住主角上限，重点写压制、破局、立威和改规则。",
        profile: buildProfile({
          coreDrive: "让主角以明显优势碾压阻力，并不断刷新他人认知。",
          readerReward: "读者每隔几章都能看到一次明确的压制和地位确立。",
          progressionUnits: ["展示底牌", "压制对手", "扩大威慑", "重写规则"],
          allowedConflictForms: ["身份误判", "势力挑衅", "高手试探"],
          forbiddenConflictForms: ["长期躲藏发育", "长时间无法反击的受虐剧情"],
          conflictCeiling: "high",
          resolutionStyle: "冲突以快速反制和高位碾压收束。",
          chapterUnit: "单章围绕一次压制、试探或立威展开。",
          volumeReward: "卷末形成新的权力格局或更大范围的承认。",
          mandatorySignals: ["强者气场", "围观震撼", "越级压制"],
          antiSignals: ["主角像普通升级文一样长期弱势", "核心优势被故意封死"],
        }),
      },
      {
        id: "story_mode_face_slap",
        name: "打脸流",
        description: "以误判、轻视和反转羞辱构成高频爽点。",
        template: "先蓄势误判，再精准反转，打脸要及时回收。",
        profile: buildProfile({
          coreDrive: "通过他人误判和后续反转持续兑现高频打脸快感。",
          readerReward: "读者不断看到轻视者被现场回收和反噬。",
          progressionUnits: ["误判铺垫", "身份反转", "公开回收", "舆论发酵"],
          allowedConflictForms: ["轻视", "公开羞辱", "资源争夺"],
          forbiddenConflictForms: ["铺垫过长却没有回收", "打脸后没有实际影响"],
          resolutionStyle: "在最需要证明自己的场合完成反转和回收。",
          chapterUnit: "单章重点制造一次误判与回收闭环。",
          volumeReward: "卷末主角从被看轻者转为不可忽视的中心人物。",
          mandatorySignals: ["误判", "反转", "当场回收"],
          antiSignals: ["只挨打不回收", "回收太轻没有爽点"],
        }),
      },
      {
        id: "story_mode_misread",
        name: "迪化流",
        description: "围绕他人误读主角、主动脑补和失控放大来制造趣味与爽感。",
        template: "误会要层层放大，并不断变成对主角有利的局面。",
        profile: buildProfile({
          coreDrive: "利用他人对主角的过度解读制造持续失控的优势局面。",
          readerReward: "读者反复获得‘别人自己脑补过头’的反差快感。",
          progressionUnits: ["误读", "脑补升级", "群体扩散", "误会兑现"],
          allowedConflictForms: ["信息不对称", "误会连锁", "群体解读偏差"],
          forbiddenConflictForms: ["直接解释清楚", "误会只持续一次就结束"],
          conflictCeiling: "medium",
          resolutionStyle: "让误会自然滚大，并转化为主角资源或声望。",
          chapterUnit: "单章围绕一次误解升级和意外收益展开。",
          volumeReward: "卷末误读体系形成稳定共识或传奇形象。",
          mandatorySignals: ["脑补", "失控传播", "主角被动受益"],
          antiSignals: ["误会强行", "所有人都很快看穿"],
        }),
      },
      {
        id: "story_mode_secret_identity",
        name: "马甲流",
        description: "用多重身份、隐藏层级和掉马风险驱动阅读欲。",
        template: "马甲要各有功能，掉马风险要形成持续钩子。",
        profile: buildProfile({
          coreDrive: "通过多重身份切换、隐藏与掉马风险制造连续张力。",
          readerReward: "读者不断看到身份差、信息差和掉马边缘的刺激感。",
          progressionUnits: ["建立马甲", "切换身份", "险些掉马", "掉马兑现"],
          allowedConflictForms: ["身份隐藏", "关系错位", "能力来源误判"],
          forbiddenConflictForms: ["所有马甲功能重复", "掉马没有后果"],
          conflictCeiling: "medium",
          resolutionStyle: "围绕身份切换解决问题，再把压力转移到下一层掉马风险。",
          chapterUnit: "单章至少推进一次身份利用或风险逼近。",
          volumeReward: "卷末形成关键掉马或更复杂的身份网。",
          mandatorySignals: ["信息差", "身份切换", "掉马钩子"],
          antiSignals: ["身份线长期静止", "马甲只是名字不同没有用途"],
        }),
      },
    ],
  },
  {
    id: "story_mode_build_root",
    name: "建设经营",
    description: "以积累、建设、经营和阶段性收成为主要推进方式的阅读模式。",
    template: "让世界随着主角行动而变得更丰富、更稳固、更有回报。",
    profile: buildProfile({
      coreDrive: "通过积累、扩张、经营和建设成果持续制造成就感。",
      readerReward: "读者能看到资源变多、地盘变稳、系统变完整的满足感。",
      progressionUnits: ["积累资源", "建设节点", "经营升级", "阶段性收成"],
      allowedConflictForms: ["资源压力", "经营竞争", "发展阻碍"],
      forbiddenConflictForms: ["反派长期压过建设主线", "全靠大战推进"],
      conflictCeiling: "medium",
      resolutionStyle: "优先用经营、组织、建设和资源调度化解问题。",
      chapterUnit: "每章推进一个可见的经营或建设单位。",
      volumeReward: "卷末给出一个更稳、更大、更丰富的成果面貌。",
      mandatorySignals: ["积累", "建设过程", "成果展示"],
      antiSignals: ["主驱动变成纯战斗文", "长期看不到收成"],
    }),
    children: [
      {
        id: "story_mode_farming",
        name: "种田流",
        description: "重视生产、积累、生活秩序和长期回暖感的建设型模式。",
        template: "重点写资源循环、土地或据点经营、关系熟化和阶段性收成。",
        profile: buildProfile({
          coreDrive: "通过一点点把生活与生产盘活，给读者稳定的回暖和积累感。",
          readerReward: "读者持续获得‘日子越来越好’和‘家底越来越厚’的满足感。",
          progressionUnits: ["播种准备", "生产积累", "邻里互动", "收成兑现"],
          allowedConflictForms: ["资源短缺", "天气与环境压力", "小范围利益摩擦"],
          forbiddenConflictForms: ["长期高压生死线", "无止境的大反派主线"],
          conflictCeiling: "low",
          resolutionStyle: "通过勤劳、组织、互助和经营慢慢解决问题。",
          chapterUnit: "单章围绕一项劳作、一项建设或一段生活改善展开。",
          volumeReward: "卷末形成一个明显更稳定、更温暖的生活阶段。",
          mandatorySignals: ["生活感", "劳作细节", "阶段收成"],
          antiSignals: ["只剩打怪和阴谋", "看不到生活改善"],
        }),
      },
      {
        id: "story_mode_management",
        name: "经营流",
        description: "以商业、组织、品牌或系统运营推动剧情。",
        template: "强调决策、运营、扩张、口碑和阶段性经营结果。",
        profile: buildProfile({
          coreDrive: "通过经营决策和组织扩张持续制造上升感。",
          readerReward: "读者反复看到业务跑起来、组织成型和口碑增长。",
          progressionUnits: ["找到突破口", "搭建流程", "扩大规模", "赢得市场"],
          allowedConflictForms: ["经营竞争", "资源调配", "团队磨合"],
          forbiddenConflictForms: ["无关的恋爱狗血长期抢戏", "经营过程被一笔带过"],
          resolutionStyle: "靠策略、运营、分工和节奏管理解决问题。",
          chapterUnit: "单章推进一个经营动作或组织问题。",
          volumeReward: "卷末形成业务升级、品牌确立或组织跃迁。",
          mandatorySignals: ["策略感", "经营动作", "结果反馈"],
          antiSignals: ["只讲结果不讲过程", "经营主线被反派线吃掉"],
        }),
      },
      {
        id: "story_mode_territory_building",
        name: "领地建设",
        description: "围绕据点、城镇、势力版图和秩序搭建持续推进。",
        template: "重点写领地升级、人口汇聚、规则建立和防线稳固。",
        profile: buildProfile({
          coreDrive: "通过把一块地、一座城或一个据点逐步经营成型，持续制造扩张与稳固的成就感。",
          readerReward: "读者不断看到领地变强、秩序成型和安全感提升。",
          progressionUnits: ["招募与安置", "设施建设", "规则落地", "外部试探回击"],
          allowedConflictForms: ["资源紧张", "边界摩擦", "管理压力", "治安危机"],
          forbiddenConflictForms: ["领地长期形同虚设", "主线被纯个人恩怨彻底带走"],
          conflictCeiling: "medium",
          resolutionStyle: "优先通过建设、治理、组织和局部反制稳定局面。",
          chapterUnit: "单章推进一个领地建设动作、治理问题或外部试探应对。",
          volumeReward: "卷末让领地规模、秩序或影响力出现清晰跃升。",
          mandatorySignals: ["据点成长", "治理动作", "秩序成型"],
          antiSignals: ["只有战争没有建设", "领地存在感越来越弱"],
        }),
      },
      {
        id: "story_mode_family_management",
        name: "家族经营",
        description: "以家业、家族关系和代际责任推动持续阅读。",
        template: "把资源经营、家族分工和内部关系变化一起写活。",
        profile: buildProfile({
          coreDrive: "通过家业扩张、家族关系重组和责任传承维持故事推进。",
          readerReward: "读者既能看到家底变厚，也能看到家族成员关系越来越成体系。",
          progressionUnits: ["家业调整", "成员磨合", "资源积累", "家族地位提升"],
          allowedConflictForms: ["家务分歧", "利益分配", "外部竞争", "代际观念冲突"],
          forbiddenConflictForms: ["狗血撕裂长期压倒经营线", "家族成员只有工具功能没有关系变化"],
          conflictCeiling: "medium",
          resolutionStyle: "通过协商、分工、经营结果和共同应对危机完成修复。",
          chapterUnit: "单章推进一次家业动作、一场家族互动或一项责任兑现。",
          volumeReward: "卷末让家族更稳固、更有凝聚力，或完成一次地位跃升。",
          mandatorySignals: ["家族协作", "家业动作", "关系重组"],
          antiSignals: ["只剩吵架不见经营", "家族线没有传承感"],
        }),
      },
    ],
  },
  {
    id: "story_mode_healing_root",
    name: "日常治愈",
    description: "以陪伴、修复、生活回暖和低烈度持续陪伴感为核心驱动。",
    template: "矛盾可以有，但不能破坏回暖感和陪伴感。",
    profile: buildProfile({
      coreDrive: "通过陪伴、修复、生活细节和关系回暖持续吸引读者。",
      readerReward: "读者反复获得安稳、温柔、回暖和情绪落地的满足感。",
      progressionUnits: ["生活日常", "陪伴修复", "小问题解决", "关系回温"],
      allowedConflictForms: ["低到中烈度困境", "关系误差", "生活压力"],
      forbiddenConflictForms: ["持续高压对抗", "黑化式推进", "无休止背刺"],
      conflictCeiling: "low",
      resolutionStyle: "优先通过陪伴、理解、日常行动和小范围修复化解问题。",
      chapterUnit: "每章围绕一个生活片段或情绪修复点展开。",
      volumeReward: "卷末让读者感到人物状态更稳、更暖、更愿意继续生活。",
      mandatorySignals: ["生活感", "安抚点", "关系回暖"],
      antiSignals: ["高压主线喧宾夺主", "治愈感被连续打断"],
    }),
    children: [
      {
        id: "story_mode_healing_daily",
        name: "治愈日常",
        description: "以日常互动、陪伴和情绪回温为主要看点的治愈模式。",
        template: "保持低烈度困境和高密度安抚点，让读者愿意停留。",
        profile: buildProfile({
          coreDrive: "靠日常陪伴和细小修复慢慢把人物带回稳定状态。",
          readerReward: "读者每几章都获得一次情绪被抚平的体验。",
          progressionUnits: ["日常互动", "情绪安抚", "关系熟化", "生活改善"],
          allowedConflictForms: ["生活小挫折", "关系别扭", "旧伤回响"],
          forbiddenConflictForms: ["大反派压顶", "长期极端痛苦不回收"],
          conflictCeiling: "low",
          resolutionStyle: "让人物通过陪伴、倾听和具体行动被一点点治好。",
          chapterUnit: "每章围绕一个情绪节点和一个安抚点展开。",
          volumeReward: "卷末让角色和读者都感到状态明显回暖。",
          mandatorySignals: ["安抚感", "生活细节", "温柔互动"],
          antiSignals: ["冲突升级成高压大戏", "读完一章只剩焦虑"],
        }),
      },
      {
        id: "story_mode_shop_daily",
        name: "小店日常",
        description: "以店铺经营和人与人来往构成稳定、治愈的追读节奏。",
        template: "顾客、邻里和经营琐事都应成为温柔推进器。",
        profile: buildProfile({
          coreDrive: "通过店铺经营、来客故事和社区互动形成持续新鲜感。",
          readerReward: "读者既能看到经营变化，也能得到温暖的陌生人故事。",
          progressionUnits: ["来客事件", "经营调整", "社区互动", "日常收束"],
          allowedConflictForms: ["小店经营压力", "人情摩擦", "生活琐事"],
          forbiddenConflictForms: ["连续恶性打压", "重悬疑或高压阴谋主导"],
          resolutionStyle: "通过待人接物、经营调整和社区互助自然化解。",
          chapterUnit: "每章推进一次来客互动或经营小事件。",
          volumeReward: "卷末让小店更有人气、更有归属感。",
          mandatorySignals: ["小店空间感", "来客故事", "社区温度"],
          antiSignals: ["只剩经营数据没有人情味", "店铺存在感越来越弱"],
        }),
      },
      {
        id: "story_mode_slow_life",
        name: "慢生活",
        description: "以节奏放缓、生活细节和日常秩序修复构成阅读吸引力。",
        template: "让风景、劳作、饮食和相处方式都成为安稳体验的一部分。",
        profile: buildProfile({
          coreDrive: "通过缓慢但持续的生活改善与身心安定感推动读者停留。",
          readerReward: "读者反复获得放松、沉浸和‘终于缓下来’的满足感。",
          progressionUnits: ["日常作息", "环境熟悉", "生活改善", "情绪回稳"],
          allowedConflictForms: ["轻微不适应", "生活小困扰", "关系疏离后的磨合"],
          forbiddenConflictForms: ["持续高压倒计时", "强反派长期追杀或压顶阴谋"],
          conflictCeiling: "low",
          resolutionStyle: "通过时间、陪伴、规律生活和小步修复慢慢化解问题。",
          chapterUnit: "单章围绕一个生活片段、一项微小改善或一次情绪缓冲展开。",
          volumeReward: "卷末让人物真正拥有一个更稳、更舒服的生活状态。",
          mandatorySignals: ["生活秩序", "松弛感", "细节沉浸"],
          antiSignals: ["为了刺激频繁硬拗大冲突", "节奏越来越躁没有呼吸感"],
        }),
      },
      {
        id: "story_mode_companion_healing",
        name: "陪伴疗愈",
        description: "把人与人之间稳定陪伴、照料和共同恢复作为主要推进器。",
        template: "矛盾要服务于靠近、信任和修复，而不是不断撕裂。",
        profile: buildProfile({
          coreDrive: "通过陪伴关系逐步建立、安全感逐步累积来带动情绪兑现。",
          readerReward: "读者不断获得被理解、被陪着走过低谷的温柔满足。",
          progressionUnits: ["接近与试探", "日常照料", "情绪松动", "关系确认"],
          allowedConflictForms: ["旧伤回避", "沟通迟滞", "生活压力", "短暂误解"],
          forbiddenConflictForms: ["反复背刺", "虐点长时间不回收", "关系恶性拉扯失控"],
          conflictCeiling: "low",
          resolutionStyle: "以耐心、陪伴、行动支持和情绪回应完成修复。",
          chapterUnit: "单章推进一次陪伴动作、一次关系松动或一次情绪落地。",
          volumeReward: "卷末让关键关系显著升温，人物更愿意相信他人和生活。",
          mandatorySignals: ["陪伴感", "信任增长", "修复落地"],
          antiSignals: ["治愈线突然变虐恋拉扯", "陪伴关系没有实质推进"],
        }),
      },
    ],
  },
  {
    id: "story_mode_comedy_root",
    name: "喜剧整活",
    description: "以反差、包袱、误会和失控回收构成主要追读动力。",
    template: "轻松不是语气标签，而是章节结构里持续兑现的笑点机制。",
    profile: buildProfile({
      coreDrive: "通过反差、包袱、误会和整活节奏持续制造轻松爽快感。",
      readerReward: "读者频繁获得笑点、反套路和情绪减压体验。",
      progressionUnits: ["设包袱", "误会升级", "反差回收", "局面失控"],
      allowedConflictForms: ["误会", "反差", "社死", "整活翻车"],
      forbiddenConflictForms: ["长篇沉重压抑线长期占主导", "笑点没有回收"],
      conflictCeiling: "medium",
      resolutionStyle: "通过包袱回收和失控场面完成释放。",
      chapterUnit: "每章至少要推进一个有效笑点结构。",
      volumeReward: "卷末形成更大的整活名场面或误会共同体。",
      mandatorySignals: ["反差", "回收", "轻松释放"],
      antiSignals: ["长时间严肃无包袱", "笑点只靠口癖和段子堆砌"],
    }),
    children: [
      {
        id: "story_mode_comedy",
        name: "搞笑流",
        description: "高频笑点、反差和轻松回收是阅读核心。",
        template: "笑点必须结构化出现，不能只靠零散金句。",
        profile: buildProfile({
          coreDrive: "靠高频包袱、反差和失控场面维持阅读快乐。",
          readerReward: "读者每章都能收获明确的轻松和好笑点。",
          progressionUnits: ["包袱铺设", "反差升级", "笑点回收", "场面翻车"],
          allowedConflictForms: ["误会", "社死", "身份反差", "认知错位"],
          forbiddenConflictForms: ["长时间沉重苦情线", "笑点稀薄又不推进剧情"],
          resolutionStyle: "用回收和升级继续抬高笑点而不是转沉重。",
          chapterUnit: "每章围绕至少一个有效包袱闭环展开。",
          volumeReward: "卷末形成标志性名场面或持续流传的笑料。",
          mandatorySignals: ["包袱", "回收", "场面感"],
          antiSignals: ["整段都很严肃", "只有吐槽没有结构"],
        }),
      },
      {
        id: "story_mode_misunderstanding_comedy",
        name: "误会喜剧",
        description: "靠多方信息差和误会扩散制造连续喜剧效果。",
        template: "误会要层层放大，但每次都要带来新的局面。",
        profile: buildProfile({
          coreDrive: "通过多方信息差导致的误会扩散维持喜剧节奏。",
          readerReward: "读者不断看到误会越滚越大却越有趣的效果。",
          progressionUnits: ["误会建立", "多方误读", "失控扩散", "喜剧回收"],
          allowedConflictForms: ["误会", "错位沟通", "集体误读"],
          forbiddenConflictForms: ["误会太快澄清", "误会只是重复同一个梗"],
          resolutionStyle: "让误会在最搞笑的位置回收，或者升级成更大笑点。",
          chapterUnit: "每章推进一层新的误解或回收节点。",
          volumeReward: "卷末形成一场大型误会名场面。",
          mandatorySignals: ["信息差", "误读", "扩散"],
          antiSignals: ["误会无后劲", "澄清过快导致节奏熄火"],
        }),
      },
      {
        id: "story_mode_absurd_subversion",
        name: "沙雕反套路",
        description: "用离谱展开、反套路回收和节奏突转制造强烈轻松感。",
        template: "反套路不只是拆预期，还要持续给出更好玩的新局面。",
        profile: buildProfile({
          coreDrive: "通过不断拆解常规预期，再给出更离谱但更成立的结果维持新鲜感。",
          readerReward: "读者持续获得‘居然还能这么来’的惊喜和轻松感。",
          progressionUnits: ["建立预期", "突然拧转", "离谱升级", "反套路回收"],
          allowedConflictForms: ["反差", "错位", "整活失控", "设定玩梗"],
          forbiddenConflictForms: ["只剩无意义发疯", "离谱但没有逻辑支点", "连续沉重正剧化"],
          conflictCeiling: "medium",
          resolutionStyle: "通过更高一层的反套路回收局面，而不是落回沉重正统冲突。",
          chapterUnit: "每章至少推进一个预期建立与反套路回收闭环。",
          volumeReward: "卷末形成高传播度的离谱名场面或反套路高潮。",
          mandatorySignals: ["意外感", "反套路", "回收闭环"],
          antiSignals: ["为了搞怪牺牲可读性", "段子化堆叠没有故事推进"],
        }),
      },
    ],
  },
  {
    id: "story_mode_mystery_root",
    name: "悬念博弈",
    description: "以信息差、推演、布局和对抗智性满足驱动追读。",
    template: "读者要持续感觉自己在往更深的真相推进。",
    profile: buildProfile({
      coreDrive: "通过信息差、推演和博弈升级持续制造想追下去的欲望。",
      readerReward: "读者不断获得谜面推进、推理快感和布局回收的满足。",
      progressionUnits: ["抛出疑点", "收集线索", "推演验证", "局势反转"],
      allowedConflictForms: ["信息差", "隐藏动机", "智性对抗"],
      forbiddenConflictForms: ["为了保密故意不讲理", "纯体力对抗吃掉推演感"],
      conflictCeiling: "high",
      resolutionStyle: "通过证据链、推演和布局完成反制。",
      chapterUnit: "每章推进一个新疑点或一个旧疑点的验证。",
      volumeReward: "卷末揭开一层更大的真相或完成一次关键博弈。",
      mandatorySignals: ["线索", "推演", "反制"],
      antiSignals: ["谜团只堆不解", "答案靠天降"],
    }),
    children: [
      {
        id: "story_mode_mystery_inference",
        name: "悬疑推演",
        description: "以线索、推理和真相揭示节奏构成阅读核心。",
        template: "每段推演都要建立在清晰线索上，不要纯作者强解。",
        profile: buildProfile({
          coreDrive: "让读者跟着线索与推演不断靠近真相。",
          readerReward: "读者持续获得‘拼图正在成型’的智性满足。",
          progressionUnits: ["提出疑点", "补充线索", "推演收束", "揭开真相"],
          allowedConflictForms: ["线索冲突", "证词矛盾", "隐藏动机"],
          forbiddenConflictForms: ["关键证据凭空出现", "为了拖延故意含糊"],
          resolutionStyle: "通过线索联动和逻辑推演完成局面突破。",
          chapterUnit: "每章推进一个关键疑点的认知变化。",
          volumeReward: "卷末揭穿核心谜面或打开更大的悬念入口。",
          mandatorySignals: ["线索感", "逻辑链", "真相逼近"],
          antiSignals: ["故弄玄虚", "结论和线索脱节"],
        }),
      },
      {
        id: "story_mode_mind_game",
        name: "智斗流",
        description: "强调布局、博弈、对手思维和反制节奏。",
        template: "对手必须像对手，博弈必须可感知。",
        profile: buildProfile({
          coreDrive: "通过多轮布局和拆招形成高黏性的智斗快感。",
          readerReward: "读者不断看到算计、反算和预判回收。",
          progressionUnits: ["布局", "试探", "反制", "收网"],
          allowedConflictForms: ["策略对抗", "心理博弈", "资源算计"],
          forbiddenConflictForms: ["对手太蠢", "所有胜利都靠主角开挂信息"],
          resolutionStyle: "通过提前布局和关键反制赢下局面。",
          chapterUnit: "每章推进一轮试探、布子或拆招。",
          volumeReward: "卷末完成一次大局收网或更高阶对手登场。",
          mandatorySignals: ["布局感", "对手压迫", "反制回收"],
          antiSignals: ["胜负没有博弈过程", "对手工具化"],
        }),
      },
      {
        id: "story_mode_survival_game",
        name: "生存博弈",
        description: "在有限资源、高压环境和规则竞争中制造持续紧张感。",
        template: "高压可以存在，但必须服务于规则推演、抉择代价和局势反制。",
        profile: buildProfile({
          coreDrive: "通过资源稀缺、环境压力和规则对抗持续制造必须做出选择的张力。",
          readerReward: "读者反复获得局势求解、代价权衡和绝境翻盘的紧绷满足。",
          progressionUnits: ["压力逼近", "规则试探", "资源争夺", "短线反制"],
          allowedConflictForms: ["资源稀缺", "规则压迫", "环境威胁", "群体博弈"],
          forbiddenConflictForms: ["纯靠运气通关", "只有肉搏没有策略", "长期重复同一种危机"],
          conflictCeiling: "high",
          resolutionStyle: "依靠规则理解、局势判断和有限资源配置完成破局。",
          chapterUnit: "单章推进一轮生存压力、规则发现或关键抉择。",
          volumeReward: "卷末完成一次阶段求生成功、规则突破或阵营格局改写。",
          mandatorySignals: ["资源压力", "选择代价", "规则利用"],
          antiSignals: ["危机廉价化", "总是同一类困境循环"],
        }),
      },
    ],
  },
  {
    id: "story_mode_relationship_root",
    name: "关系情感",
    description: "以关系推进、情感兑现和人物之间的拉扯变化作为主驱动。",
    template: "重点不是单纯堆冲突，而是让关系状态持续变化并兑现读者期待。",
    profile: buildProfile({
      coreDrive: "通过人物关系的靠近、拉扯、错位与回收，持续制造追读动力。",
      readerReward: "读者不断获得关系变化、情感张力和关键情绪兑现。",
      progressionUnits: ["关系建立", "情绪拉扯", "信任变化", "节点兑现"],
      allowedConflictForms: ["关系误差", "情感错位", "现实阻力", "价值观摩擦"],
      forbiddenConflictForms: ["关系线长期停滞", "无意义狗血反复打转", "情感推进被其他线长期吞没"],
      conflictCeiling: "medium",
      resolutionStyle: "通过情绪交流、关系行动和关键选择完成推进或修复。",
      chapterUnit: "每章推进一个关系节点、情绪变化或彼此认知变化。",
      volumeReward: "卷末让关键关系发生明确变化或完成一次高价值情感兑现。",
      mandatorySignals: ["关系张力", "情绪节点", "兑现感"],
      antiSignals: ["关系原地踏步", "只有设定没有互动"],
    }),
    children: [
      {
        id: "story_mode_romantic_tension",
        name: "恋爱拉扯",
        description: "以暧昧、靠近、退缩和关系试探制造持续吸引力。",
        template: "拉扯要有温差和推进，不能只靠误会拖延。",
        profile: buildProfile({
          coreDrive: "通过双向吸引与现实阻力之间的反复拉扯维持情感张力。",
          readerReward: "读者不断看到关系升温、试探失控和情绪回收。",
          progressionUnits: ["试探靠近", "边界碰撞", "情绪失衡", "关系推进"],
          allowedConflictForms: ["暧昧错位", "表达失败", "现实阻力", "价值观差异"],
          forbiddenConflictForms: ["故意降智不说人话", "拖太久不推进", "关系线完全被外部主线压没"],
          conflictCeiling: "medium",
          resolutionStyle: "通过互动升级、情绪承认和行动选择完成关系推进。",
          chapterUnit: "单章推进一个情感试探、认知变化或关系边界松动。",
          volumeReward: "卷末让关系进入新阶段，或完成一次高浓度情绪确认。",
          mandatorySignals: ["暧昧感", "双向张力", "靠近兑现"],
          antiSignals: ["只有误会拖延", "没有实质关系变化"],
        }),
      },
      {
        id: "story_mode_chasing_wife",
        name: "追妻火葬场",
        description: "以前期伤害或错失为前提，靠后续追偿、悔意和关系重建推进。",
        template: "核心是追偿和重建，不是单方面反复伤害。",
        profile: buildProfile({
          coreDrive: "通过失去后的追偿、悔改和关系重建制造强烈情绪牵引。",
          readerReward: "读者持续获得‘该追的在追、该还的在还、该痛的有回应’的满足。",
          progressionUnits: ["后悔显现", "追偿行动", "关系试炼", "重建兑现"],
          allowedConflictForms: ["信任断裂", "旧伤反扑", "补偿落差", "现实阻碍"],
          forbiddenConflictForms: ["追偿只停留在嘴上", "二次伤害无限循环", "被追一方完全失去主体性"],
          conflictCeiling: "medium",
          resolutionStyle: "用持续行动、代价承担和边界尊重推进关系重建。",
          chapterUnit: "单章推进一次追偿动作、一次旧伤碰撞或一次关系松动。",
          volumeReward: "卷末形成清晰的关系修复阶段或强力情绪回收。",
          mandatorySignals: ["悔意落地", "行动补偿", "边界重建"],
          antiSignals: ["只会口头道歉", "关系重建没有成本"],
        }),
      },
      {
        id: "story_mode_ensemble_bond",
        name: "群像羁绊",
        description: "通过多人关系网、共同经历和羁绊演化形成阅读黏性。",
        template: "群像不是名单堆砌，而是每个角色都要在关系网里发挥作用。",
        profile: buildProfile({
          coreDrive: "通过多人互动和羁绊变化让故事始终有新的关系火花。",
          readerReward: "读者不断获得角色之间的新连接、站队变化和情感共振。",
          progressionUnits: ["关系串联", "群体事件", "立场变化", "羁绊加深"],
          allowedConflictForms: ["立场差异", "责任分歧", "情感错位", "团队压力"],
          forbiddenConflictForms: ["群像角色长期工具化", "只剩主角独走", "关系网不发生变化"],
          conflictCeiling: "medium",
          resolutionStyle: "通过团队互动、共同经历和角色间的选择完成关系演化。",
          chapterUnit: "单章推进一个群体互动节点或关键角色对之间的关系变化。",
          volumeReward: "卷末让群像结构更稳，或让队伍/关系网进入新阶段。",
          mandatorySignals: ["群体互动", "关系联动", "角色互相成就"],
          antiSignals: ["角色只报名字不干活", "群像线断裂成单人独角戏"],
        }),
      },
    ],
  },
  {
    id: "story_mode_growth_root",
    name: "成长冒险",
    description: "以升级、探索、闯关和阶段性突破构成追读主动力。",
    template: "读者需要持续感知到人物能力、认知或世界边界在扩展。",
    profile: buildProfile({
      coreDrive: "通过成长曲线、探索推进和阶段突破持续制造前进感。",
      readerReward: "读者反复获得变强、解锁新区域和达成新门槛的满足。",
      progressionUnits: ["获得目标", "挑战升级", "突破瓶颈", "进入新区域"],
      allowedConflictForms: ["试炼", "探索风险", "阶段门槛", "成长阵痛"],
      forbiddenConflictForms: ["长期停滞不成长", "只有升级数值没有体验变化", "探索线长期缺席"],
      conflictCeiling: "high",
      resolutionStyle: "通过训练、实践、探索和阶段性突破完成破局。",
      chapterUnit: "每章推进一个成长动作、一次探索发现或一段闯关反馈。",
      volumeReward: "卷末让人物到达更高阶段，或打开一片更大的冒险空间。",
      mandatorySignals: ["成长感", "突破感", "世界扩展"],
      antiSignals: ["升级口头化", "冒险线停摆"],
    }),
    children: [
      {
        id: "story_mode_growth_leveling",
        name: "升级成长",
        description: "围绕角色能力、认知和阶段门槛突破构建阅读快感。",
        template: "升级不只写结果，还要写门槛、代价和兑现。",
        profile: buildProfile({
          coreDrive: "通过清晰可感的成长曲线和阶段突破持续拉动阅读。",
          readerReward: "读者不断看到能力、地位或认知层级获得实质提升。",
          progressionUnits: ["积累条件", "卡点受阻", "完成突破", "展示提升"],
          allowedConflictForms: ["瓶颈", "试炼", "资源不足", "同层竞争"],
          forbiddenConflictForms: ["成长全靠旁白略过", "突破没有代价和铺垫", "升级后没有任何兑现"],
          conflictCeiling: "high",
          resolutionStyle: "通过积累、训练、实战和关键顿悟完成成长突破。",
          chapterUnit: "单章推进一次积累、一次卡点试探或一次成长兑现。",
          volumeReward: "卷末完成一个清晰等级、境界或阶段跃迁。",
          mandatorySignals: ["成长门槛", "突破反馈", "阶段变化"],
          antiSignals: ["升级像流水账", "能力提升没有剧情后果"],
        }),
      },
      {
        id: "story_mode_adventure_exploration",
        name: "探索冒险",
        description: "以新地图、新文明和未知风险驱动阅读新鲜感。",
        template: "探索要带来真正的新信息、新选择和新危险。",
        profile: buildProfile({
          coreDrive: "通过不断进入未知区域、接触新规则和发现新秘密保持阅读新鲜感。",
          readerReward: "读者持续获得开图、发现与未知感兑现。",
          progressionUnits: ["进入新区域", "发现新规则", "遭遇风险", "带出新认知"],
          allowedConflictForms: ["环境威胁", "未知规则", "探索竞争", "文明差异"],
          forbiddenConflictForms: ["场景只是换皮", "探索没有新信息产出", "连续宅在原地不推进世界边界"],
          conflictCeiling: "high",
          resolutionStyle: "通过观察、应对、适应和局部突破打开更深层探索。",
          chapterUnit: "单章推进一次新发现、一次环境应对或一次地图探索。",
          volumeReward: "卷末打开新的区域层级、秘密入口或冒险目标。",
          mandatorySignals: ["未知感", "发现感", "地图扩展"],
          antiSignals: ["探索空转", "新区域没有存在意义"],
        }),
      },
      {
        id: "story_mode_dungeon_challenge",
        name: "副本闯关",
        description: "以阶段关卡、规则破解和通关反馈形成强节奏推进。",
        template: "副本不是重复打怪，要写清目标、机制、风险和通关奖励。",
        profile: buildProfile({
          coreDrive: "通过阶段性关卡挑战和规则破解形成连续的推进快感。",
          readerReward: "读者不断获得过关、破局和奖励兑现的满足。",
          progressionUnits: ["进入副本", "识别机制", "破解难点", "通关结算"],
          allowedConflictForms: ["关卡机制", "时间压力", "队伍配合", "资源限制"],
          forbiddenConflictForms: ["副本机制全靠硬抗", "通关后没有奖励反馈", "副本重复到没有新意"],
          conflictCeiling: "high",
          resolutionStyle: "通过规则识别、团队配合和关键执行完成通关。",
          chapterUnit: "单章推进一个关卡节点、一个机制破解或一次通关反馈。",
          volumeReward: "卷末完成一段完整副本征程，获得显著奖励或更高阶入口。",
          mandatorySignals: ["机制感", "闯关反馈", "奖励兑现"],
          antiSignals: ["关卡同质化", "只剩数值堆砌没有机制"],
        }),
      },
    ],
  },
];
