ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"arcClimax" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"arcEnd" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"arcMidpoint" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"arcStart" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"castRole" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"fear" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"firstImpression" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"innerNeed" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"misbelief" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"moralLine" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"outerGoal" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"relationToProtagonist" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"secret" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"storyFunction" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS"wound" TEXT;

ALTER TABLE "BookAnalysis" ADD COLUMN IF NOT EXISTS"pendingManualRecovery" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GenerationJob" ADD COLUMN IF NOT EXISTS"pendingManualRecovery" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ImageGenerationTask" ADD COLUMN IF NOT EXISTS"pendingManualRecovery" BOOLEAN NOT NULL DEFAULT false;
