import type { WorldReferenceMode } from "@write-now/shared/types/worldWizard";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import {
  type WorldAxiomSuggestionPromptInput,
  type WorldConsistencyPromptInput,
  type WorldDeepeningQuestionsPromptInput,
  type WorldImportExtractionPromptInput,
  type WorldInspirationConceptCardLocalizationPromptInput,
  type WorldInspirationConceptCardPromptInput,
  type WorldLayerGenerationPromptInput,
  type WorldLayerLocalizationPromptInput,
  type NovelThemeWorldGenerationPromptInput,
  type WorldPropertyOptionsPromptInput,
  type WorldReferenceInspirationPromptInput,
  type WorldStructureBackfillPromptInput,
  type WorldStructureSectionPromptInput,
  type WorldVisualizationPromptInput,
} from "./world.promptTypes";
import {
  worldAxiomSuggestionSchema,
  worldConceptCardSchema,
  worldConsistencyIssuesSchema,
  worldDeepeningQuestionsSchema,
  worldImportExtractionSchema,
  worldLooseObjectSchema,
  novelThemeWorldGenerationSchema,
  worldPropertyOptionsPayloadSchema,
} from "./world.promptSchemas";
import { worldReferenceInspirationPayloadSchema } from "../../../services/world/worldReferenceSchema";
import { worldStructuredDataSchema, worldStructureSectionOutputSchema } from "../../../services/world/worldSchemas";
import { worldVisualizationDraftSchema } from "../../../services/world/worldVisualizationSchema";
import {
  buildStructureSectionInstructions,
} from "../../../services/world/worldServiceShared";

function buildReferenceModeLabel(mode: WorldReferenceMode | null | undefined): string {
  switch (mode) {
    case "extract_base":
      return "提取原作世界基底";
    case "tone_rebuild":
      return "借用原作气质与结构重建";
    case "adapt_world":
    default:
      return "基于原作做架空改造";
  }
}

function sanitizeLooseWorldObject(value: unknown, allowedKeys: string[], label: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} 必须返回 JSON 对象。`);
  }

  const record = value as Record<string, unknown>;
  const normalizedAllowedKeys = new Set(allowedKeys.map((key) => key.trim()).filter(Boolean));
  if (normalizedAllowedKeys.size === 0) {
    throw new Error(`${label} 缺少允许字段配置。`);
  }

  const filteredEntries = Object.entries(record).filter(([key, fieldValue]) => {
    if (!normalizedAllowedKeys.has(key)) {
      return false;
    }
    return fieldValue != null;
  });

  if (filteredEntries.length === 0) {
    throw new Error(`${label} 没有返回任何允许字段。`);
  }

  return Object.fromEntries(filteredEntries);
}

function normalizeWorldStructureSectionPayload(
  value: z.infer<typeof worldStructureSectionOutputSchema>,
  input: WorldStructureSectionPromptInput,
): z.infer<typeof worldStructureSectionOutputSchema> {
  const arraySections = new Set(["locations"]);
  const shouldReturnArray = arraySections.has(input.section);

  if (shouldReturnArray) {
    if (!Array.isArray(value)) {
      throw new Error(`world.structure.generate 在 section=${input.section} 时必须返回数组。`);
    }
    return value;
  }

  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`world.structure.generate 在 section=${input.section} 时必须返回对象。`);
  }
  if (input.section === "factions") {
    const record = value as Record<string, unknown>;
    if (!Array.isArray(record.factions) && !Array.isArray(record.forces)) {
      throw new Error("world.structure.generate 在 section=factions 时必须返回包含 factions 或 forces 数组的对象。");
    }
  }
  return value;
}

export const worldReferenceInspirationPrompt: PromptAsset<
  WorldReferenceInspirationPromptInput,
  z.infer<typeof worldReferenceInspirationPayloadSchema>
> = {
  id: "world.reference.inspiration",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldReferenceInspirationPayloadSchema,
  render: (input) => [
    new SystemMessage([
      "你是参考作品世界分析师。",
      "你的任务不是重写一套无关的新故事，而是从参考材料中提炼“可保留的世界基底”与“可用于架空改造的决策边界”，为后续世界观构建提供稳定底板。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "conceptCard": {',
      '    "worldType": "...",',
      '    "templateKey": "custom",',
      '    "coreImagery": ["..."],',
      '    "tone": "...",',
      '    "keywords": ["..."],',
      '    "summary": "..."',
      "  },",
      '  "anchors": [',
      "    {",
      '      "id": "anchor-1",',
      '      "label": "...",',
      '      "content": "..."',
      "    }",
      "  ],",
      '  "seedPackage": {',
      '    "rules": [',
      "      {",
      '        "id": "reference-rule-1",',
      '        "name": "...",',
      '        "summary": "...",',
      '        "cost": "...",',
      '        "boundary": "...",',
      '        "enforcement": "..."',
      "      }",
      "    ],",
      '    "factions": [',
      "      {",
      '        "id": "reference-faction-1",',
      '        "name": "...",',
      '        "position": "...",',
      '        "doctrine": "...",',
      '        "goals": ["..."],',
      '        "methods": ["..."],',
      '        "representativeForceIds": ["reference-force-1"]',
      "      }",
      "    ],",
      '    "forces": [',
      "      {",
      '        "id": "reference-force-1",',
      '        "name": "...",',
      '        "type": "...",',
      '        "factionId": "reference-faction-1",',
      '        "summary": "...",',
      '        "baseOfPower": "...",',
      '        "currentObjective": "...",',
      '        "pressure": "...",',
      '        "leader": "...",',
      '        "narrativeRole": "..."',
      "      }",
      "    ],",
      '    "locations": [',
      "      {",
      '        "id": "reference-location-1",',
      '        "name": "...",',
      '        "terrain": "...",',
      '        "summary": "...",',
      '        "narrativeFunction": "...",',
      '        "risk": "...",',
      '        "entryConstraint": "...",',
      '        "exitCost": "...",',
      '        "controllingForceIds": ["reference-force-1"]',
      "      }",
      "    ]",
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      '2. conceptCard.templateKey 固定为 "custom"，不得改动。',
      "3. 只能基于参考材料提炼，不得凭空发明大量原文没有支撑的世界结构。",
      "4. 允许做低风险归纳，但禁止把具体剧情桥段、主角感情推进、角色个人动机误写成世界基底。",
      "5. 输出目标是“世界参考资产”，不是剧情梗概，也不是题材改写提案。",
      "",
      "conceptCard 要求：",
      "1. worldType：概括参考世界的基本类型，要稳、准、可复用。",
      "2. coreImagery：提炼最有辨识度的世界意象，优先保留场景感、秩序感、压迫感、行业感或社会质感。",
      "3. tone：概括世界整体气质，如冷硬、压抑、荒诞、粗粝、秩序森严等，不要写空话。",
      "4. keywords：提炼世界层关键词，优先写制度、环境、结构、生态，而不是剧情词。",
      "5. summary：必须说明“哪些应保留、哪些可以改造”，明确这套参考模式真正值得借的世界底板与可变动边界，不能泛泛重写题材。",
      "",
      "anchors 要求：",
      "1. anchors 必须提供 4-6 个，不能少于 4 个，不能多于 6 个。",
      "2. 优先覆盖以下维度中的核心部分：现实基底、城市地点结构、社会压力、行业生态、关系结构、世界边界。",
      "3. 每个 anchor 都必须是“世界层”或“世界-故事接口层”的稳定锚点，能直接影响后续架空改造决策。",
      "4. 不要写具体剧情桥段、具体男女主关系推进、单一角色的私密动机。",
      "5. label 必须简洁清楚，content 必须具体说明这个锚点为何值得保留或如何作为改造基底。",
      "",
      "seedPackage 总规则：",
      "1. seedPackage 用于提取“可直接沿用或轻改的原作世界设定资产”。",
      "2. rules、factions、forces、locations 四类都允许为空数组，但如果材料中有明确可提取内容，应优先保留，不要因为保守而全部清空。",
      "3. 不要为了凑结构胡乱编造；没有依据就留空数组。",
      "4. 优先提取：世界规则、阵营立场、具体组织/势力、地点/场景，这四类可复用内容。",
      "",
      "rules 要求：",
      "1. 只收录真正具有世界约束力的规则、秩序、代价机制或运行逻辑。",
      "2. summary 写规则本身，cost 写遵守/违背/使用该规则的代价，boundary 写适用边界，enforcement 写这条规则如何被维持。",
      "3. 不要把主角个人习惯、剧情偶发事件误写成规则。",
      "",
      "factions 要求：",
      "1. 只提取在世界中有稳定立场、组织性或群体意志的阵营。",
      "2. position 写其在世界格局中的站位，doctrine 写其核心信条或价值倾向。",
      "3. goals 和 methods 必须体现这个阵营如何运作、争夺或施压。",
      "",
      "forces 要求：",
      "1. forces 是更具体、可在故事中落地的组织、部门、团体、权力节点或行动主体。",
      "2. 必须与某个 faction 建立清晰归属，若无清晰归属再保守处理。",
      "3. summary、baseOfPower、currentObjective、pressure、narrativeRole 都要具体，体现其在世界中的可用价值。",
      "",
      "locations 要求：",
      "1. 只提取具有世界辨识度和叙事功能的地点，不要随便抓普通地点名。",
      "2. summary 要说明地点特征，narrativeFunction 要说明其在故事层面的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点如何产生限制、代价或压力。",
      "",
      "质量要求：",
      "1. 整体结果必须像“世界参考拆解卡”，而不是随手摘抄的笔记。",
      "2. conceptCard、anchors、seedPackage 三部分必须互相一致，不得彼此打架。",
      "3. 优先保留对后续世界改造最有用的硬结构，不要被零碎细节拖走。",
    ].join("\n")),
    new HumanMessage(input.userPrompt),
  ],
};

export const worldVisualizationPrompt: PromptAsset<
  WorldVisualizationPromptInput,
  z.infer<typeof worldVisualizationDraftSchema>
> = {
  id: "world.visualization.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldVisualizationDraftSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观可视化抽取器。",
      "你的任务是把输入中的世界设定、阵营关系、地理结构和时间演变，提炼为可直接用于可视化展示的结构化 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "factionGraph": {',
      '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
      '    "edges": [{"source":"faction-1","target":"faction-2","relation":"同盟|合作|支援|对抗|敌对|统属|压制|贸易|竞争|中立|关联"}]',
      "  },",
      '  "powerTree": [{"level":"L1","description":"..."}],',
      '  "geographyMap": {',
      '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
      '    "edges": [{"source":"geo-1","target":"geo-2","relation":"相邻|通道|隔绝|控制","routeType":"road|river|sea|portal|trade|military|border|other","distanceHint":"...","direction":"north|south|east|west|center|northeast|northwest|southeast|southwest","risk":"..."}]',
      "  },",
      '  "timeline": [{"year":"...","event":"..."}]',
      "}",
      "",
      "全局硬规则：",
      "1. 所有 label、relation、description、event、year 都必须使用简体中文。",
      "2. 只能抽取文本中明确存在或可低风险推断的信息，不得凭空编造世界结构。",
      "3. 输出目标是“可视化结构抽取”，不是世界观赏析，也不是剧情总结。",
      "4. 各部分之间必须一致，不得出现 factionGraph、geographyMap、timeline 互相打架的情况。",
      "",
      "factionGraph 规则：",
      "1. 必须优先反映真实势力关系，不要用模糊泛化关系替代明确关系。",
      "2. nodes 数量控制在 4-12 个之间，优先保留核心势力、关键种族、主要组织或国家主体。",
      "3. type 只能使用：state、faction、race、organization、other。",
      "4. edge.relation 只能使用：同盟、合作、支援、对抗、敌对、统属、压制、贸易、竞争、中立、关联。",
      "5. 不要为了凑节点而加入无叙事价值的小势力或一次性提及对象。",
      "6. 如果两个势力关系不明确，就不要强行连边。",
      "",
      "powerTree 规则：",
      "1. powerTree 用于抽取权力层级、力量阶梯、统治结构或资源支配结构。",
      "2. 每项 level 应体现层级位置，如 L1、L2、L3。",
      "3. description 必须写清这一层代表什么权力/力量层，而不是空泛写“上层”“中层”。",
      "4. 若文本没有明确力量层级，可保守提炼最稳定的层级结构，不要硬造复杂等级体系。",
      "",
      "geographyMap 规则：",
      "1. geographyMap 用于提取关键地点之间的空间位置与连通关系，而不是列地点清单。",
      "2. nodes 应优先保留对世界运行、势力分布或故事推进有意义的核心地点。",
      "3. x/y 使用 0-100 的相对地图坐标：x 越大越偏东，y 越大越偏南；中心地点约为 50/50。",
      "4. directionHint 必须与 x/y 大体一致；文本没有明确方向时，允许根据叙事层级做保守布局，但不要假装有精确距离。",
      "5. regionType 用于区分大陆、国家、区域、城市、地标、边境、路线或其他。",
      "6. edges.relation 只能使用：相邻、通道、隔绝、控制。",
      "7. routeType 用于标记道路、河流、海路、传送、商道、军道、边界或其他；没有依据时用 other。",
      "8. 不要把纯剧情场景、一次性地点或无空间结构价值的地点塞进地图。",
      "9. 若地点之间关系不明确，不要强行连边。",
      "",
      "timeline 规则：",
      "1. timeline 只提取对世界格局有影响的重要历史节点、阶段变化或关键事件。",
      "2. year 可以是具体年份，也可以是阶段性时间表达，如“旧纪元末期”“三年前”“新朝建立初期”。",
      "3. event 必须简洁写清“发生了什么变化”，不要写成长段故事。",
      "4. 不要把普通背景介绍或局部人物经历误写成世界时间线节点。",
      "",
      "质量要求：",
      "1. 优先保留“能让前端画出图来”的结构信息，而不是泛分析。",
      "2. 节点和边都要克制，宁可少而清楚，不要堆得像杂货架。",
      "3. 如果某部分信息确实不足，可以返回空数组，但不要用编造内容填满。",
      "4. id 要稳定、简洁、可引用；同一节点在 edges 中必须正确对应。",
      "",
      "输出必须严格符合 worldVisualizationDraftSchema。",
    ].join("\n")),
    new HumanMessage(input.worldPromptSource),
  ],
};

export const worldInspirationConceptCardPrompt: PromptAsset<
  WorldInspirationConceptCardPromptInput,
  z.infer<typeof worldConceptCardSchema>
> = {
  id: "world.inspiration.concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观灵感概念卡提炼器。",
      "你的任务是根据输入的灵感文本、世界类型提示和可用素材，提炼出一张可直接用于后续世界观设计的“世界灵感概念卡”。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "所有文本字段都必须使用简体中文。",
      "",
      "输出结构必须严格为：",
      "{",
      '  "worldType":"...",',
      `  "templateKey":"${input.templateKeysText}",`,
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"3-5句中文摘要"',
      "}",
      "",
      "全局硬规则：",
      "1. templateKey 必须从给定可用值中选择，不得自造、改写或留空。",
      "2. 只能基于输入材料提炼，不得凭空发明完整世界设定。",
      "3. 允许做低风险归纳，但禁止把模糊印象写成过强结论。",
      "4. 输出目标是“世界灵感概念卡”，不是剧情梗概，不是人物设定，也不是世界百科。",
      "",
      "字段要求：",
      "1. worldType：",
      "   - 优先结合 worldTypeHint 与灵感文本判断。",
      "   - 应概括世界的基础类型，例如都市现实变体、末世废土、架空王朝、近未来高压社会等。",
      "   - 要稳、准、可用于后续分流，不要写成空泛大词。",
      "",
      "2. templateKey：",
      "   - 必须在给定可用模板中选最贴合的一项。",
      "   - 若输入信息混合度高，也要优先选择最能承载后续展开的主模板。",
      "",
      "3. coreImagery：",
      "   - 提取 3-6 个最有辨识度的世界意象。",
      "   - 优先保留空间感、秩序感、行业感、压迫感、技术感、宗教感、社会质感等“能让人一眼看见这个世界”的意象。",
      "   - 不要写剧情桥段，不要写单个角色动作。",
      "",
      "4. tone：",
      "   - 用一句短语概括这个世界的整体气质，如冷硬压抑、破败混乱、华丽腐朽、克制诡谲等。",
      "   - 不要写成“很精彩”“很有氛围”这种空话。",
      "",
      "5. keywords：",
      "   - 提取 4-8 个关键词。",
      "   - 优先体现世界结构、规则来源、主要压迫、运行逻辑、社会生态或核心气味。",
      "   - 不要和 coreImagery 机械重复。",
      "",
      "6. summary：",
      "   - 必须是 3-5 句中文摘要。",
      "   - 要说明这个世界最值得保留的核心底板是什么、它给人的第一读感是什么、后续适合往什么方向展开。",
      "   - 不要写成剧情简介，不要泛泛复述题材。",
      "",
      "提炼原则：",
      "1. 如果输入是原始灵感，应优先帮用户“收拢方向”，而不是继续发散。",
      "2. 如果输入已经分段提取或带有检索素材，应优先保留其中最稳定、最可复用的世界底板。",
      "3. 如果信息不足，宁可输出更稳的概念卡，也不要硬补复杂设定。",
      "4. 不要把人物关系、具体事件推进、主线冲突误写成世界概念。",
      "",
      "质量要求：",
      "1. 概念卡应让人看完就知道“这是个什么世界、什么气味、后续能往哪走”。",
      "2. 各字段之间必须一致，不能 worldType 是一种世界，tone 和 keywords 却像另一套东西。",
      "3. 结果必须适合进入后续世界观设计流程，而不是停留在灵感随笔层。",
    ].join("\n")),
    new HumanMessage([
      `模式=${input.mode}`,
      `世界类型提示=${input.worldTypeHint}`,
      `灵感文本=${input.promptText}`,
      `是否分段提取=${input.extracted ? "是" : "否"}`,
      `原文长度=${input.originalLength} 字符`,
      `可用世界观素材检索=${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldInspirationConceptCardLocalizationPrompt: PromptAsset<
  WorldInspirationConceptCardLocalizationPromptInput,
  z.infer<typeof worldConceptCardSchema>
> = {
  id: "world.inspiration.localize_concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观概念卡本地化编辑。",
      "你的任务是把输入的概念卡内容翻译并润色为自然、准确、可直接展示与继续使用的简体中文版本。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "必须严格保持原有 JSON 结构不变，输出结构只能是：",
      "{",
      '  "worldType":"...",',
      '  "templateKey":"...",',
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"..."',
      "}",
      "",
      "全局硬规则：",
      "1. 所有可展示文本都必须改写为自然、流畅、准确的简体中文。",
      "2. 必须严格保留原有字段名、字段层级、数组长度和基本语义，不得新增、删除、重命名字段。",
      "3. templateKey 属于结构字段，必须保持原样，不得翻译、改写或替换。",
      "4. 不得改变概念卡原本的世界类型判断、意象方向、气质定位和关键词含义。",
      "5. 不得补写新的世界设定、剧情信息或解释性内容。",
      "",
      "本地化要求：",
      "1. 不是机械直译，而是要转写成符合中文世界观策划语境的自然表达。",
      "2. 若原文存在明显生硬、重复、翻译腔或英文思维表达，应在不改变原意的前提下润色。",
      "3. coreImagery 和 keywords 应保持短词或短语风格，简洁、有辨识度，不要扩写成长句。",
      "4. tone 应像中文策划中真实会使用的气质描述，不要翻得僵硬。",
      "5. summary 应保持概念卡摘要风格，清楚、凝练，不要写成散文或说明书。",
      "",
      "质量要求：",
      "1. 输出结果应像一张成熟的中文世界灵感概念卡，而不是翻译稿。",
      "2. 各字段之间必须一致，不得出现 worldType 是一种世界、tone 和 keywords 却像另一种世界的情况。",
      "3. 若输入中已有中文且表达自然，应尽量保留，不要为了“翻译”而硬改。",
      "",
      "输出必须严格符合 worldConceptCardSchema。",
    ].join("\n")),
    new HumanMessage(input.conceptCardJson),
  ],
};

export const worldPropertyOptionsPrompt: PromptAsset<
  WorldPropertyOptionsPromptInput,
  z.infer<typeof worldPropertyOptionsPayloadSchema>
> = {
  id: "world.property_options.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldPropertyOptionsPayloadSchema,
  render: (input) => {
    const isReferenceMode = Boolean(input.referenceMode);

    return [
      new SystemMessage(
        isReferenceMode
          ? [
              "你是参考作品架空改造规划师。",
              "你的任务不是重写一套无关的新世界，而是基于参考作品的世界锚点、保留要求和改造边界，提炼出“正式生成世界前必须先决定”的关键世界决策项。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策",',
              '      "choices": [',
              "        {",
              '          "id": "choice-a",',
              '          "label": "方向 A",',
              '          "summary": "说明这个方向如何改造原作世界"',
              "        }",
              "      ]",
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 每个 option 都必须包含 2-4 个 choices。",
              "5. choices 必须是互斥分支，而不是同义改写、强弱版本或描述角度变化。",
              "6. 不要生成角色动机、感情推进、具体桥段、单章冲突这类故事层选项。",
              "7. 只能围绕“世界层”或“世界-故事接口层”做决策设计。",
              "",
              "决策项要求：",
              "1. 每个 option 都必须是真正会改变后续世界构建方向的前置决策，而不是伪选项。",
              "2. name 必须简洁、清楚、可直接给用户点选，不要写成长句。",
              "3. description 必须说明“这个属性决定什么”以及“为什么要现在先决定”，不能空泛。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能重复 description。",
              "",
              "choices 设计规则：",
              "1. 每个 choice 都必须代表一条清晰可分叉的架空改造路线。",
              "2. choices 之间要体现真正不同的世界走法，例如现实保留程度、秩序显隐方式、压迫结构来源、规则公开程度、地点系统组织方式等。",
              "3. 不要输出只是措辞不同的近义分支。",
              "4. summary 必须说明“这一分支会如何改造原作世界”，并点出边界与代价感。",
              "",
              "参考改造原则：",
              "1. 决策项必须围绕参考作品的世界基底展开，而不是借壳起一套无关新世界。",
              "2. 优先保留真正定义原作气质的底层结构，再在可改造边界内做分叉设计。",
              "3. 如果某个方向会让原作核心气质失真，应在该 choice.summary 中体现这种边界。",
              "4. 优先考虑现实基底、城市规则、社会压迫结构、地点系统、势力网络、公开与隐秘边界这类真正影响世界的核心轴。",
              "",
              "质量要求：",
              "1. options 之间尽量覆盖不同 targetLayer，不要全部挤在同一层。",
              "2. 每个 option 都应让用户一眼明白“我到底在决定哪个世界轴”。",
              "3. 输出结果应直接服务于下一步世界生成，而不是停留在概念讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
          : [
              "你是小说世界生成器的前置决策规划师。",
              "你的任务是在正式生成世界之前，先提炼出一组真正值得用户先做决定的“关键世界属性选项”。",
              "这些选项不是装饰性问题，而是会直接影响后续世界构建方向的前置决策轴。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策"',
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 不要生成“世界名称”“世界简介”“整体风格”这类过于宽泛或无实际选择价值的伪选项。",
              "",
              "属性设计要求：",
              "1. 每个 option 都必须是具体、可选择、会影响后续世界搭建方向的关键属性。",
              "2. name 必须简洁明确，让用户一眼知道自己在决定什么。",
              "3. description 必须说明：这个属性具体控制世界的哪一部分，以及为什么值得在生成前优先确定。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能和 description 同义重复。",
              "",
              "生成原则：",
              "1. 这些选项应延续“先选属性、再补细节”的思路，优先抓真正影响世界成型方向的分歧点。",
              "2. 属性之间尽量独立，但组合后应能自然拼成一套连贯世界。",
              "3. 优先考虑基础层、力量层、社会层、文化层、历史层、冲突层，不要全部堆在一个层面。",
              "4. 可以参考经典网文世界搭建逻辑，但不要落入陈词滥调，要保留辨识度。",
              "5. 必须结合世界类型、模板说明、概念摘要、核心意象、关键词、基调和用户原始灵感综合判断。",
              "",
              "质量要求：",
              "1. 每个属性都应让用户看完后能自然做选择，而不是还要再解释一遍。",
              "2. 不要输出空泛大词，例如“世界复杂度”“设定深度”“故事张力”。",
              "3. 输出结果应直接服务下一步世界生成，而不是停留在灵感讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
      ),
      new HumanMessage(
        isReferenceMode
          ? [
              `参考方式：${buildReferenceModeLabel(input.referenceMode)}`,
              input.referenceAnchors && input.referenceAnchors.length > 0
                ? `原作世界锚点：\n${input.referenceAnchors.map((item) => `- ${item.label}：${item.content}`).join("\n")}`
                : "",
              input.preserveElements && input.preserveElements.length > 0
                ? `必须保留：${input.preserveElements.join("、")}`
                : "",
              input.allowedChanges && input.allowedChanges.length > 0
                ? `允许改造：${input.allowedChanges.join("、")}`
                : "",
              input.forbiddenElements && input.forbiddenElements.length > 0
                ? `禁止偏离：${input.forbiddenElements.join("、")}`
                : "",
              `请生成 ${input.optionsCount} 个“架空改造前必须先决定”的关键世界决策项。`,
              "补充要求：",
              "1. 每个决策项都必须是世界层或世界-故事接口层的改造轴。",
              "2. 每个决策项都必须给出 2-4 个互斥分支 choices，让用户能真正做路线选择。",
              "3. choices 之间必须体现不同架空方向，而不是描述角度变化。",
              "4. 不要偏离原作世界基底去重新发明无关新世界。",
            ].filter(Boolean).join("\n")
          : [
              `世界类型：${input.worldType}`,
              `模板：${input.templateName}`,
              `模板说明：${input.templateDescription}`,
              input.classicElements.length > 0 ? `可参考的经典元素：${input.classicElements.join("、")}` : "",
              input.pitfalls.length > 0 ? `需要避开的常见坑点：${input.pitfalls.join("、")}` : "",
              `世界概念摘要：${input.conceptSummary}`,
              input.coreImagery.length > 0 ? `核心意象：${input.coreImagery.join("、")}` : "",
              input.keywords.length > 0 ? `关键词：${input.keywords.join("、")}` : "",
              input.tone.trim() ? `整体基调：${input.tone.trim()}` : "",
              input.sourcePrompt.trim() ? `用户原始灵感：${input.sourcePrompt.trim()}` : "",
              input.ragContext?.trim() ? `可参考素材：${input.ragContext.trim()}` : "",
              `请生成 ${input.optionsCount} 个“适合在正式生成世界前先做决定”的关键世界属性选项。`,
              "补充要求：",
              "1. 优先覆盖真正重要的世界分歧点，而不是宽泛项。",
              "2. 属性之间尽量分布到不同层级，组合后能形成完整世界。",
              "3. 每个属性都要让用户一眼明白自己在决定什么。",
            ].filter(Boolean).join("\n")
      ),
    ];
  },
};

export const worldDeepeningQuestionsPrompt: PromptAsset<
  WorldDeepeningQuestionsPromptInput,
  z.infer<typeof worldDeepeningQuestionsSchema>
> = {
  id: "world.deepening.questions",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldDeepeningQuestionsSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观补全提问器。",
      "你的任务是基于当前世界设定，挑出最值得优先追问的 2-3 个关键补全问题，帮助后续世界生成继续往下走。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "每个数组项必须严格使用以下结构：",
      "{",
      '  "priority":"required|recommended|optional",',
      '  "question":"...",',
      '  "quickOptions":["...", "...", "..."],',
      '  "targetLayer":"foundation|power|society|culture|history|conflict",',
      '  "targetField":"..."',
      "}",
      "",
      "全局硬规则：",
      "1. 只能输出 2-3 个问题，不得少于 2 个，不得多于 3 个。",
      "2. 所有文本必须使用简体中文。",
      "3. 只能基于输入中的世界名称、描述、已有数据和可用参考素材来提问，不得凭空发散到无关方向。",
      "4. 问题必须是“继续生成世界前最值得先问的缺口”，而不是泛泛聊天问题。",
      "",
      "问题设计要求：",
      "1. 每个问题都必须指向一个真正会影响后续世界搭建方向的关键缺口。",
      "2. 优先提问最能决定世界走向、规则形态、社会结构、冲突来源或历史底板的问题。",
      "3. 不要问太宽的问题，例如“你还想补充什么”“这个世界还有什么特点”。",
      "4. 不要问角色动机、具体剧情桥段、感情推进这类故事层问题，除非它直接影响世界层结构。",
      "",
      "priority 规则：",
      "1. required：缺了这个问题，后续世界生成容易跑偏或塌掉。",
      "2. recommended：补上会明显提升世界完整度与可写性，但短期缺失仍可继续。",
      "3. optional：属于锦上添花型补充，不是当前最硬缺口。",
      "",
      "question 规则：",
      "1. 必须写成用户一看就能回答的自然问题。",
      "2. 问法要具体、清楚，不要用抽象术语。",
      "3. 每个问题都应尽量只问一个核心点，不要把多个问题塞进一句话。",
      "",
      "quickOptions 规则：",
      "1. 必须提供 2-4 个简洁候选答案，全部使用简体中文。",
      "2. quickOptions 应该帮助用户快速选择方向，而不是重复 question。",
      "3. 不同选项之间必须体现真实分叉，不能只是同义改写。",
      "4. 选项要短、准、可直接点选，不要写成长句分析。",
      "",
      "targetLayer 规则：",
      "1. 只能从 foundation、power、society、culture、history、conflict 中选择。",
      "2. 必须准确对应这个问题主要作用于哪一层世界结构。",
      "",
      "targetField 规则：",
      "1. 必须写清这个问题要补的是哪个具体字段或决策点。",
      "2. targetField 要简洁稳定，适合后续系统消费，例如“规则公开程度”“力量来源”“社会控制方式”“历史断层原因”。",
      "",
      "选择优先级原则：",
      "1. 优先挑“最少提问、最大增益”的问题。",
      "2. 若已有 dataJson 已经较完整，就不要重复问已明确的信息。",
      "3. 若 ragContext 提供了强参考方向，可以优先追问那些会决定参考素材如何落地的关键分叉。",
      "4. 2-3 个问题之间尽量分布在不同层级，不要全部挤在同一层，除非某一层确实是当前最大缺口。",
      "",
      "质量要求：",
      "1. 输出的问题要让用户感觉“这几个问题确实问到了点子上”。",
      "2. 不要为了凑数量提价值很低的问题。",
      "3. 整体结果必须能直接用于下一步世界补全流程。",
    ].join("\n")),
    new HumanMessage([
      `世界名称：${input.worldName}`,
      `世界描述：${input.description || "无"}`,
      `当前数据：${input.dataJson}`,
      `可用参考素材：${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldConsistencyPrompt: PromptAsset<
  WorldConsistencyPromptInput,
  z.infer<typeof worldConsistencyIssuesSchema>
> = {
  id: "world.consistency.check",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConsistencyIssuesSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观一致性审校器。",
      "你的任务是检查当前世界设定是否存在明确冲突、规则打架或高风险不一致点，并输出结构化问题列表。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "如果没有问题，只输出 []。",
      "",
      "每项结构必须严格为：",
      '{"severity":"warn|error","code":"...","message":"中文问题概述","detail":"中文详细说明","targetField":"description|background|geography|cultures|magicSystem|politics|races|religions|technology|conflicts|history|economy|factions"}',
      "",
      "全局硬规则：",
      "1. message 和 detail 必须使用简体中文。",
      "2. 只能基于给定世界公理、核心设定和检索补充进行判断，不得脑补未提供的设定。",
      "3. 只指出真正的冲突或明显风险，不要泛泛而谈，不要为了凑数量制造问题。",
      "4. 如果证据不足，不要强行判定为问题。",
      "",
      "审校重点：",
      "1. 世界公理与具体设定是否冲突。",
      "2. 不同字段之间是否存在规则打架、因果断裂或层级不兼容。",
      "3. 设定是否会导致明显不可运行、不可持续或互相抵消的结构风险。",
      "4. 地理、政治、经济、宗教、种族、技术、魔法、历史、冲突体系之间是否存在显著不自洽。",
      "",
      "severity 规则：",
      "1. error：存在明确冲突、无法同时成立、或会直接破坏世界运行逻辑的问题。",
      "2. warn：当前未必绝对冲突，但存在明显高风险、解释缺口或后续极易写崩的点。",
      "",
      "字段要求：",
      "1. code：使用简洁稳定、可复用的英文或下划线风格问题编码，不要写成长句。",
      "2. message：一句话点明问题核心，让人一眼看懂哪里冲突。",
      "3. detail：具体说明为什么这是问题，冲突发生在哪两层或哪几个字段之间。",
      "4. targetField：必须从以下字段中选择最主要的问题落点：description、background、geography、cultures、magicSystem、politics、races、religions、technology、conflicts、history、economy、factions。",
      "",
      "质量要求：",
      "1. 优先输出最关键、最会影响后续世界生成和写作的问题。",
      "2. 若多个问题本质相同，应合并，不要重复报同一类风险。",
      "3. detail 必须具体，不能只重复 message。",
      "4. 输出结果必须可直接供后续修正流程使用。",
    ].join("\n")),
    new HumanMessage([
      `世界名：${input.worldName}`,
      `世界公理：${input.axioms || "无"}`,
      `核心设定：${input.coreSettingsJson}`,
      `检索补充：${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldLayerGenerationPrompt: PromptAsset<
  WorldLayerGenerationPromptInput,
  z.infer<typeof worldLooseObjectSchema>
> = {
  id: "world.layer.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        `你是世界观分层构建器，当前只负责生成 layer=${input.layerKey} 对应字段。`,
        "你的任务不是重写整套世界观，而是在既有世界基础上，为当前层补出可直接用于小说创作的结构化设定。",
        "",
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        `输出字段只能来自：${input.targetFields.join(", ")}。`,
        "不得新增字段，不得输出目标字段之外的任何键。",
        "每个字段的值必须是可直接展示给作者阅读的简体中文文本字符串。",
        "禁止把字段值写成 JSON 对象、数组、嵌套结构、键值表或代码式结构。",
        "如果某层天然包含多个条目，请在同一个字符串内用自然语言分段或换行表达，不要输出嵌套对象。",
        "",
        "全局硬规则：",
        "1. 必须严格遵守：世界公理、模板约束、用户前置蓝图选择、既有已生成内容。",
        "2. 只能在现有基础上做补全与细化，不得推翻前面层已成立的设定。",
        "3. 若输入信息不足，必须做保守补全，优先给出低风险、可成立的设定，不要胡乱发散。",
        "4. 所有字段值必须使用简体中文。",
        "5. 输出必须是可直接落入世界设定库的结果，而不是分析说明或摘要。",
        "",
        "生成原则：",
        "1. 当前层必须与前面层形成因果关系、结构关联或运行关联，不能写成孤立描述。",
        "2. 每个字段都应回答“这个世界具体是怎么运作的”，而不是只写概念标签。",
        "3. 优先生成对后续剧情、人物、冲突、资源流动、秩序运转真正有作用的设定。",
        "4. 不要写空泛表达，如“社会复杂”“文化多元”“势力纷争”。必须具体说明复杂在哪里、多元在哪里、如何纷争。",
        "",
        "一致性要求：",
        "1. 不得与 existing 中已有内容冲突。",
        "2. 若某项设定必须承接 blueprint 或 summary 中的方向，必须明确体现承接关系。",
        "3. 若 classicElements 可参考，应吸收其有效结构，但不能机械复读模板说明。",
        "4. 若 pitfalls 已指出常见坑点，必须主动避开这些问题，不要把风险直接写进设定。",
        "",
        "质量要求：",
        "1. 每个字段都要具体、清楚、可用于写作，不要停留在百科式空描述。",
        "2. 设定应体现世界的运行逻辑、约束边界和叙事价值。",
        "3. 如果当前层天然依赖上层设定，必须显式体现这种依赖，而不是另起炉灶。",
        "",
        "边界规则：",
        "1. 不要输出总结段、前言、后记或解释说明。",
        "2. 不要补写 targetFields 之外的附加设定。",
        "3. 不要因为信息不足而留空字段；应尽量给出稳妥可用的内容。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `name=${input.worldName}`,
        `worldType=${input.worldType}`,
        `template=${input.templateName}`,
        `templateDescription=${input.templateDescription}`,
        `classicElements=${input.classicElements.join(" | ") || "none"}`,
        `pitfalls=${input.pitfalls.join(" | ") || "none"}`,
        `axioms=${input.axioms || "none"}`,
        `summary=${input.summary || "none"}`,
        "blueprint=",
        input.blueprintPromptBlock,
        `existing=${input.existingJson}`,
        `ragContext=${input.ragContext || "none"}`,
        "",
        `请只生成当前 layer=${input.layerKey} 所需字段，并确保字段仅来自：${input.targetFields.join(", ")}。`,
      ].join("\n")
    ),
  ],
  postValidate: (output, input) =>
    sanitizeLooseWorldObject(
      output,
      input.targetFields,
      `world.layer.generate(${input.layerKey})`,
    ),
};

export const worldLayerLocalizationPrompt: PromptAsset<
  WorldLayerLocalizationPromptInput,
  z.infer<typeof worldLooseObjectSchema>
> = {
  id: "world.layer.localize",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        "你是世界观设定文本本地化助手。",
        "你的任务是将输入 JSON 对象中所有“展示给用户看的字段值”改写为自然、准确、可直接使用的简体中文。",
        "",
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        "结构硬规则：",
        "1. 必须保持字段名完全不变。",
        "2. 不得新增字段、删除字段或调整层级结构。",
        `3. 输出字段只能来自当前层允许字段：${input.layerFields.join(", ")}。`,
        "",
        "内容规则：",
        "1. 必须保留原设定语义，不得改变世界规则、结构关系、因果逻辑或设定边界。",
        "2. 必须保留专有名词含义；若原专有名词已有合理中文形式，应优先使用自然中文表达。",
        "3. 不得补写新设定，不得删减已有有效信息。",
        "4. 不得把模糊表述擅自具体化为新的世界事实。",
        "",
        "本地化要求：",
        "1. 所有字段值都必须改写为简体中文。",
        "2. 不是机械翻译，而是要转写成符合中文小说世界设定语境的自然表达。",
        "3. 若原文存在英文思维、生硬直译、重复或不通顺表达，应在不改变原意前提下优化。",
        "4. 数组中的每一项也必须本地化，但要保持原有数量与对应关系不变。",
        "",
        "质量要求：",
        "1. 输出结果必须像可直接进入世界设定库的中文成稿，而不是翻译稿。",
        "2. 各字段值之间必须保持一致，不得出现术语前后不统一。",
        "3. 不要输出空泛润色，优先保证准确、稳定、可复用。",
        "",
        "边界规则：",
        "1. 如果输入中某些值本来已经是自然中文，可保留或仅做轻微润色，不要为了改而改。",
        "2. 如果某些 ID、代码式字段值属于结构标识而非展示文本，不要误翻。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `layer=${input.layerKey}`,
        `fields=${input.layerFields.join(",")}`,
        `input=${input.sourcePayloadJson}`,
      ].join("\n")
    ),
  ],
  postValidate: (output, input) =>
    sanitizeLooseWorldObject(
      output,
      input.layerFields,
      `world.layer.localize(${input.layerKey})`,
    ),
};

export const worldImportExtractionPrompt: PromptAsset<
  WorldImportExtractionPromptInput,
  z.infer<typeof worldImportExtractionSchema>
> = {
  id: "world.import.extract",
  version: "v1",
  taskType: "fact_extraction",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldImportExtractionSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观导入抽取器。",
      "你的任务是从输入文本中提取可直接导入系统的世界设定 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "输出字段必须且只能包括：",
      "name, description, worldType, background, geography, magicSystem, politics, cultures, races, religions, technology, history, economy, conflicts, factions, templateKey, axioms。",
      "",
      "全局硬规则：",
      "1. 所有可展示文本必须使用简体中文。",
      "2. 只能提取输入文本中明确存在或可低风险归纳的信息，不得凭空补写完整设定。",
      "3. 如果某个字段在原文中没有足够依据，必须保守处理，优先返回空字符串、空数组或最小可成立内容，不要硬编。",
      "4. 输出目标是“世界设定导入”，不是总结文章，也不是赏析报告。",
      "5. 各字段之间必须一致，不得互相冲突。",
      "",
      "字段提取原则：",
      "1. name：提取世界名称；若原文未明确给出，使用最稳妥、最贴近文本的概括性名称，不要乱造花哨名字。",
      "2. description：概括世界整体面貌与核心特征，简洁但具体，不要写空话。",
      "3. worldType：提取世界基础类型，如都市异变、架空王朝、末世废土、近未来高压社会等，必须稳、准、可用于后续分类。",
      "4. background：提取世界形成背景、时代处境、根本局势或大环境前提。",
      "5. geography：提取关键地理格局、空间结构、区域分布或地点系统。",
      "6. magicSystem：提取超凡体系、力量规则、能力来源、代价与边界；若无相关内容，保守留空。",
      "7. politics：提取政体、权力结构、治理方式、统治关系或政治对抗。",
      "8. cultures：提取风俗、价值观、社会习惯、礼制、禁忌或文化分层。",
      "9. races：提取种族、族群、阶层型生物群体或特殊人群划分；没有则留空。",
      "10. religions：提取宗教、信仰体系、神话信奉、祭祀秩序或精神权威来源；没有则留空。",
      "11. technology：提取技术水平、生产力形态、工具系统、工业/信息/机械特征。",
      "12. history：提取关键历史阶段、断层、重大事件、旧秩序遗产或历史创伤。",
      "13. economy：提取资源流动、财富来源、产业结构、交换机制、生存成本或经济压迫结构。",
      "14. conflicts：提取世界层的核心矛盾、长期冲突来源、结构性对抗，不要写成单一剧情事件。",
      "15. factions：提取稳定存在的势力、组织、国家、阵营、集团或权力主体。",
      "16. templateKey：根据文本内容保守归类到最贴近的模板键；若文本无足够依据，使用最稳妥的默认归类，不要自造模板名。",
      "17. axioms：提取世界公理、硬性规则、不可违背的底层约束或默认运行逻辑。",
      "",
      "抽取质量要求：",
      "1. 优先提取对后续小说创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人经历、具体剧情桥段、单次事件误写成世界层字段。",
      "3. 不要把相邻字段写成同义重复，例如 background、history、description 不应只是换说法重复同一段。",
      "4. 若输入文本明显偏故事简介，也要尽量只抽世界层信息，过滤人物线与情节线噪音。",
      "",
      "缺失处理规则：",
      "1. 不确定时优先保守，不要脑补。",
      "2. 没有明确宗教/种族/魔法/科技内容时，不要为了结构完整而强行生成。",
      "3. 若 factions 可抽取为数组或列表内容，应尽量保留为可用的结构性描述，而不是模糊概括。",
      "",
      "输出必须严格符合 worldImportExtractionSchema。",
    ].join("\n")),
    new HumanMessage(input.content),
  ],
};

export const worldStructureBackfillPrompt: PromptAsset<
  WorldStructureBackfillPromptInput,
  z.infer<typeof worldStructuredDataSchema>
> = {
  id: "world.structure.backfill",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructuredDataSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界结构化提取器。",
      "你的任务是根据输入文本，提取可直接进入系统使用的世界结构数据。",
      "这不是赏析，不是总结，也不是自由补全，而是把文本中的世界层信息整理为稳定的 JSON 结构。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "JSON 结构必须严格为：",
      "{",
      '  "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '  "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
      '  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '  "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
      '  "relations": {',
      '    "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
      '    "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 只能提取文本里明确存在或可低风险推断的信息，不得凭空编造完整世界结构。",
      "2. 所有值必须使用简体中文。",
      "3. 不要增加额外字段，不要改字段名，不要删字段层级。",
      "4. 若某类信息确实缺失，应保守返回空数组或最小可成立内容，不要硬编。",
      "5. 各部分之间必须自洽，不得互相冲突。",
      "",
      "字段判定规则：",
      "1. profile：用于概括这个世界的整体身份、气质、主题和核心矛盾，必须站在“世界层”而不是“角色层”总结。",
      "2. rules：用于提取这个世界默认成立的规则、代价、边界、禁忌和共同后果。",
      "3. factions：是抽象阵营、立场、路线、阶层板块或意识形态阵营。",
      "4. forces：是具体组织、圈层、公司、部门、帮会、机构、网络或可落地行动主体。",
      "5. locations：是具有世界辨识度和叙事功能的地点，不是随便提到的普通场景。",
      "6. relations：用于提取 forces 之间的关系，以及 force 对 location 的控制关系。",
      "",
      "关键区分要求：",
      "1. 像“社会压力机制”“行业运作规则”“默认人际法则”“生存代价”“资源约束”这类世界默认机制，必须写进 rules，不要塞进 factions 或 forces。",
      "2. faction 写的是‘哪一类人/立场/路线’，force 写的是‘具体谁在执行、控制、施压’。",
      "3. 若一个对象只有抽象立场，没有明确组织实体，优先归入 factions；若它能作为具体行动单位出现，优先归入 forces。",
      "",
      "profile 要求：",
      "1. summary：概括世界最核心的面貌与运行现实，不要写剧情简介。",
      "2. identity：写清这个世界的基本身份，例如工业废土都市、权力高压王朝、行业丛林社会等。",
      "3. tone：写世界整体气质，如冷硬、压抑、粗粝、腐朽、诡谲，不要空话。",
      "4. themes：提取世界层主题，不要写单个角色命题。",
      "5. coreConflict：写世界最核心、最长期成立的结构性矛盾。",
      "",
      "rules 要求：",
      "1. axioms 只收录真正具有世界约束力的规则。",
      "2. 每条 axiom 都要写清：规则是什么、代价是什么、边界在哪里、如何被维持。",
      "3. taboo 是世界明确不能碰的禁忌、红线或高压触发点。",
      "4. sharedConsequences 是这个世界里多数人共同承担的默认后果或系统性代价。",
      "",
      "factions / forces 要求：",
      "1. factions 必须体现立场、信条、目标和方法差异，不要做成空泛标签。",
      "2. representativeForceIds 必须尽量对应真正代表该 faction 的具体 force。",
      "3. forces 必须写清其权力来源、当前目标、施压方式和叙事作用。",
      "4. 没有明确 leader 时可保守处理，但不要乱造人名。",
      "",
      "locations 要求：",
      "1. 只保留真正重要的地点。",
      "2. summary 要说明地点特征，narrativeFunction 要说明它在故事中的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点为何有门槛、有压力或有代价。",
      "",
      "relations 要求：",
      "1. forceRelations 只记录真正有意义的关系，不要把所有对象机械连边。",
      "2. relation 要写清关系类型，tension 要写清当前紧张点，detail 要说明关系为何成立。",
      "3. locationControls 只在文本能支持 force 与 location 存在控制、占据、管理、封锁、渗透等关系时再写。",
      "",
      "质量要求：",
      "1. 优先提取对后续创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人动机、具体剧情桥段、感情推进写进世界结构。",
      "3. 不要让 profile、rules、factions、forces 彼此换说法重复。",
      "4. 输出结果必须像一份可直接落库的世界结构草案，而不是读书笔记。",
    ].join("\n")),
    new HumanMessage(input.promptSource),
  ],
};

export const novelThemeWorldGenerationPrompt: PromptAsset<
  NovelThemeWorldGenerationPromptInput,
  z.infer<typeof novelThemeWorldGenerationSchema>
> = {
  id: "novel.world.generate_from_theme",
  version: "v2",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  repairPolicy: {
    maxAttempts: 0,
  },
  semanticRetryPolicy: {
    maxAttempts: 0,
  },
  outputSchema: novelThemeWorldGenerationSchema,
  render: (input) => [
    new SystemMessage([
      "你是网文小说的本书世界设计师。",
      "你的任务是根据一本小说的主题、卖点、读者承诺和类型信息，生成“这本书专属使用”的世界结构数据。",
      "这不是外部世界库百科，也不是剧情大纲；输出必须服务于后续角色、大纲、章节和一致性生成。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "title": "...",',
      '  "coverSummary": "...",',
      '  "worldType": "...",',
      '  "structuredData": {',
      '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '    "factions": [{"id":"faction-1","name":"...","position":"...","goals":["..."],"representativeForceIds":["force-1"]}],',
      '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","currentObjective":"...","pressure":"..."}],',
      '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","controllingForceIds":["force-1"]}],',
      '    "relations": {',
      '      "forceRelations": [{"sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"..."}],',
      '      "locationControls": [{"forceId":"force-1","locationId":"location-1","relation":"..."}]',
      "    }",
      "  }",
      "}",
      "",
      "输出容量硬约束：",
      "1. 这里只生成可开书的世界种子，不是完整百科；后续在世界手册中按需要扩写。",
      "2. 名称、id、类型等短字段不超过 16 个汉字；说明字段不超过 24 个汉字；数组每项不超过 12 个汉字且最多 2 项。",
      "3. 不重复解释同一规则、势力或地点；除 JSON 键名和 id 外，全部文本控制在约 1,800 个汉字以内。",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      "2. 世界必须紧扣本书主题，不得生成一套与小说卖点无关的通用百科。",
      "3. 世界设定必须能约束后续生成：力量有代价，秩序有执行者，冲突有来源，地点有叙事功能。",
      "4. 不要写主角个人剧情，不要替小说生成完整大纲，不要把单次事件当成世界规则。",
      "5. 允许根据小说信息做合理补全；如果信息不足，要生成稳妥、低风险、可继续扩展的本书舞台。",
      input.openingOnly
        ? "6. 当前只准备开篇切片：仅生成前 3-5 章会直接读取的规则、势力和地点，不扩写远期百科。"
        : "6. 当前生成可持续扩展的本书世界基础。",
      "",
      "内容数量要求：",
      "1. rules.axioms 生成 2-3 条硬规则。",
      "2. factions 生成 1-2 个与本书直接相关的阵营或立场板块。",
      "3. forces 生成 2-3 个会行动或施压的具体势力、组织或机构。",
      "4. locations 生成 2-3 个会反复使用的舞台地点。",
      "5. relations 中只连接真正有意义的势力关系和地点控制关系，不要机械全连接。",
      "",
      "字段质量要求：",
      "1. title 要像一个可展示的世界名，不要只是小说名。",
      "2. coverSummary 用 1-2 句说明读者一眼能看到的世界面貌。",
      "3. profile.summary 要说明“这个世界长什么样、如何运行、为什么适合这本书”。",
      "4. rules 每条 axiom 必须写清规则、代价、边界和执行方式。",
      "5. faction 是立场或阶层板块，force 是具体执行者；不要混淆。",
      "6. location 必须有风险或叙事功能。",
      "7. forbidden/taboo/sharedConsequences 要帮助后续生成避免违背世界规则。",
      "",
      "面向生成链的要求：",
      "1. 角色生成应该能从 forces/factions 中找到身份、归属、冲突来源。",
      "2. 大纲生成应该能从 locations/coreConflict 中找到舞台和长期矛盾。",
      "3. 章节生成应该能从 rules/taboo/sharedConsequences 中获得不可违背的约束。",
      "4. 这份世界是本书副本，可以之后保存到世界库；不要假设它已经是通用模板。",
    ].join("\n")),
    new HumanMessage([
      `小说标题：${input.novelTitle}`,
      `小说简介：${input.description || "未填写"}`,
      `目标读者：${input.targetAudience || "未填写"}`,
      `核心卖点：${input.bookSellingPoint || "未填写"}`,
      `前30章承诺：${input.first30ChapterPromise || "未填写"}`,
      `商业标签：${input.commercialTags.length > 0 ? input.commercialTags.join("、") : "未填写"}`,
      `主类型：${input.genreName || "未选择"}`,
      `主故事模式：${input.primaryStoryModeName || "未选择"}`,
      `副故事模式：${input.secondaryStoryModeName || "未选择"}`,
      `准备范围：${input.openingOnly ? "开篇 3-5 章世界切片" : "本书世界基础"}`,
      input.storyMacroContext?.trim() ? `故事宏观规划：\n${input.storyMacroContext.trim()}` : "",
      input.bookContractContext?.trim() ? `书级创作约定：\n${input.bookContractContext.trim()}` : "",
    ].join("\n")),
  ],
};

export const worldStructureSectionPrompt: PromptAsset<
  WorldStructureSectionPromptInput,
  z.infer<typeof worldStructureSectionOutputSchema>
> = {
  id: "world.structure.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructureSectionOutputSchema,
  render: (input) => [
    new SystemMessage(
      [
        `你是世界结构化补全器，当前只负责补全 section=${input.section} 对应的 JSON。`,
        "你的任务不是重写整套世界结构，而是在现有结构基础上，为指定 section 补出可直接落库的结构化内容。",
        "",
        "只输出一个合法 JSON，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        buildStructureSectionInstructions(input.section),
        "",
        "全局硬规则：",
        "1. 只能补全当前 section 对应的数据，不得输出其他 section 的内容。",
        "2. 不要破坏已有 ID；如果沿用现有实体，必须复用当前结构中的 id。",
        "3. 不得编造与输入文本、当前结构或绑定建议明显冲突的信息。",
        "4. 如果信息不足，必须做保守补全，优先补“低风险、可成立、能落地”的结构，不要硬造复杂设定。",
        "5. 所有文本值必须使用简体中文。",
        "",
        "一致性要求：",
        "1. 输出内容必须与当前结构保持连续，不得推翻已成立的世界规则、阵营关系、地点功能或既有绑定。",
        "2. 若当前 section 涉及实体复用，优先延续现有命名、归属与关系网络。",
        "3. 若当前绑定建议给出了优先连接方向，应尽量沿用，除非与输入文本明显冲突。",
        "",
        "section 补全规则：",
        "1. 如果 section=factions，必须同时考虑 factions 和 forces 的区分与联动。",
        "2. 禁止把社会压力机制、行业规则、人际法则、默认秩序、普遍代价这类世界默认机制写进 factions / forces；这些内容属于 rules。",
        "3. faction 写抽象阵营、立场、路线；force 写具体组织、部门、圈层、公司、帮会、机构、网络等行动主体。",
        "4. 如果 section=locations，必须填写 narrativeFunction、risk、entryConstraint、exitCost，且内容必须具体可用，不能空泛。",
        "5. 如果 section=relations，只允许输出 forceRelations 和 locationControls，不得新增其他关系块。",
        "6. relations 必须只连接真正有依据的实体，不要机械连边。",
        "",
        "质量要求：",
        "1. 输出必须像可直接进入世界结构库的成稿，而不是分析说明。",
        "2. 每个字段都要具体、稳定、可供后续创作使用，避免“势力复杂”“地点危险”“关系紧张”这类空话。",
        "3. 优先补足真正影响世界运行和叙事推进的硬结构，不要被零碎细节带偏。",
        "4. 若当前 section 天然依赖其他 section，必须体现这种结构关联，而不是孤立书写。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        input.promptSource,
        "",
        "当前结构：",
        JSON.stringify(input.currentStructure, null, 2),
        "",
        "当前绑定建议：",
        JSON.stringify(input.currentBindingSupport, null, 2),
      ].join("\n"),
    ),
  ],
  postValidate: (output, input) => normalizeWorldStructureSectionPayload(output, input),
};

export const worldAxiomSuggestionPrompt: PromptAsset<
  WorldAxiomSuggestionPromptInput,
  z.infer<typeof worldAxiomSuggestionSchema>
> = {
  id: "world.axioms.suggest",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldAxiomSuggestionSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界公理设计器。",
      "你的任务是为当前世界生成 5 条“核心公理”，作为后续世界构建、设定补全和剧情展开的最高约束层。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "数组元素必须全部是字符串，且全部使用简体中文。",
      "必须精确输出 5 条，不能多也不能少。",
      "",
      "全局硬规则：",
      "1. 每条公理都必须是“能约束后续生成”的硬规则，而不是口号、主题句或世界简介。",
      "2. 公理必须能直接影响后续世界搭建，例如限制代价、规定秩序、定义冲突来源、划定边界条件、明确默认后果。",
      "3. 只能基于输入中的世界类型、模板说明、世界摘要和蓝图约束来生成，不得脱离这些信息另起一套世界。",
      "4. 如果信息不足，优先生成低风险、通用但有约束力的公理，不要空泛发散。",
      "",
      "公理设计要求：",
      "1. 至少应覆盖以下关键约束中的大部分：代价、秩序、冲突来源、边界条件、默认后果、资源约束、权力限制、公开与隐秘规则。",
      "2. 每条公理都应回答“这个世界默认怎么运作，违反后会怎样，哪些事不能无代价发生”。",
      "3. 公理必须具体，例如可以约束力量使用、身份流动、资源获取、组织秩序、信息传播、社会压迫、越界代价等。",
      "4. 不要写成‘世界很残酷’‘人心复杂’‘强者为尊’这类空泛判断，除非它被具体化为可执行约束。",
      "5. 5 条公理之间尽量分工明确，不要换说法重复同一个意思。",
      "",
      "表达要求：",
      "1. 每条公理尽量写成一句完整、清楚、可直接引用的约束句。",
      "2. 不要写得太长，但必须足够具体，能拿去约束后续世界生成。",
      "3. 语言要像世界设定中的底层规则，而不是宣传文案或文学抒情。",
      "",
      "质量要求：",
      "1. 看完这 5 条，应该能大致理解这个世界的运行底线。",
      "2. 这些公理要能帮助后续自动生成避免跑偏、避免设定失真、避免无代价乱开。",
      "3. 不要生成互相冲突的公理。",
    ].join("\n")),
    new HumanMessage([
      `世界名=${input.worldName}`,
      `世界类型=${input.worldType}`,
      `模板=${input.templateName}`,
      `模板说明=${input.templateDescription}`,
      `世界摘要=${input.description}`,
      "蓝图约束：",
      input.blueprintPromptBlock,
    ].join("\n")),
  ],
};
